/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVisitantesRouteImport } from './routes/_authenticated/visitantes'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPalavrasRouteImport } from './routes/_authenticated/palavras'
import { Route as AuthenticatedMusicosRouteImport } from './routes/_authenticated/musicos'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedHinosRouteImport } from './routes/_authenticated/hinos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCongregacoesRouteImport } from './routes/_authenticated/congregacoes'
import { Route as AuthenticatedAtendimentosRouteImport } from './routes/_authenticated/atendimentos'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedCultosIndexRouteImport } from './routes/_authenticated/cultos.index'
import { Route as AuthenticatedCultoInteligenteIndexRouteImport } from './routes/_authenticated/culto-inteligente.index'
import { Route as AuthenticatedCultosIdRouteImport } from './routes/_authenticated/cultos.$id'
import { Route as AuthenticatedCultoInteligenteHistoricoRouteImport } from './routes/_authenticated/culto-inteligente.historico'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisitantesRoute = AuthenticatedVisitantesRouteImport.update({
  id: '/visitantes',
  path: '/visitantes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPalavrasRoute = AuthenticatedPalavrasRouteImport.update({
  id: '/palavras',
  path: '/palavras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMusicosRoute = AuthenticatedMusicosRouteImport.update({
  id: '/musicos',
  path: '/musicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHinosRoute = AuthenticatedHinosRouteImport.update({
  id: '/hinos',
  path: '/hinos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCongregacoesRoute =
  AuthenticatedCongregacoesRouteImport.update({
    id: '/congregacoes',
    path: '/congregacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtendimentosRoute =
  AuthenticatedAtendimentosRouteImport.update({
    id: '/atendimentos',
    path: '/atendimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCultosIndexRoute =
  AuthenticatedCultosIndexRouteImport.update({
    id: '/cultos/',
    path: '/cultos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCultoInteligenteIndexRoute =
  AuthenticatedCultoInteligenteIndexRouteImport.update({
    id: '/culto-inteligente/',
    path: '/culto-inteligente/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCultosIdRoute = AuthenticatedCultosIdRouteImport.update({
  id: '/cultos/$id',
  path: '/cultos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCultoInteligenteHistoricoRoute =
  AuthenticatedCultoInteligenteHistoricoRouteImport.update({
    id: '/culto-inteligente/historico',
    path: '/culto-inteligente/historico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/congregacoes': typeof AuthenticatedCongregacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hinos': typeof AuthenticatedHinosRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/musicos': typeof AuthenticatedMusicosRoute
  '/palavras': typeof AuthenticatedPalavrasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/visitantes': typeof AuthenticatedVisitantesRoute
  '/culto-inteligente/historico': typeof AuthenticatedCultoInteligenteHistoricoRoute
  '/cultos/$id': typeof AuthenticatedCultosIdRoute
  '/culto-inteligente/': typeof AuthenticatedCultoInteligenteIndexRoute
  '/cultos/': typeof AuthenticatedCultosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/congregacoes': typeof AuthenticatedCongregacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hinos': typeof AuthenticatedHinosRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/musicos': typeof AuthenticatedMusicosRoute
  '/palavras': typeof AuthenticatedPalavrasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/visitantes': typeof AuthenticatedVisitantesRoute
  '/culto-inteligente/historico': typeof AuthenticatedCultoInteligenteHistoricoRoute
  '/cultos/$id': typeof AuthenticatedCultosIdRoute
  '/culto-inteligente': typeof AuthenticatedCultoInteligenteIndexRoute
  '/cultos': typeof AuthenticatedCultosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/atendimentos': typeof AuthenticatedAtendimentosRoute
  '/_authenticated/congregacoes': typeof AuthenticatedCongregacoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hinos': typeof AuthenticatedHinosRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/musicos': typeof AuthenticatedMusicosRoute
  '/_authenticated/palavras': typeof AuthenticatedPalavrasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/visitantes': typeof AuthenticatedVisitantesRoute
  '/_authenticated/culto-inteligente/historico': typeof AuthenticatedCultoInteligenteHistoricoRoute
  '/_authenticated/cultos/$id': typeof AuthenticatedCultosIdRoute
  '/_authenticated/culto-inteligente/': typeof AuthenticatedCultoInteligenteIndexRoute
  '/_authenticated/cultos/': typeof AuthenticatedCultosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/agenda'
    | '/atendimentos'
    | '/congregacoes'
    | '/dashboard'
    | '/hinos'
    | '/insights'
    | '/musicos'
    | '/palavras'
    | '/relatorios'
    | '/visitantes'
    | '/culto-inteligente/historico'
    | '/cultos/$id'
    | '/culto-inteligente/'
    | '/cultos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/agenda'
    | '/atendimentos'
    | '/congregacoes'
    | '/dashboard'
    | '/hinos'
    | '/insights'
    | '/musicos'
    | '/palavras'
    | '/relatorios'
    | '/visitantes'
    | '/culto-inteligente/historico'
    | '/cultos/$id'
    | '/culto-inteligente'
    | '/cultos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/pricing'
    | '/reset-password'
    | '/_authenticated/agenda'
    | '/_authenticated/atendimentos'
    | '/_authenticated/congregacoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/hinos'
    | '/_authenticated/insights'
    | '/_authenticated/musicos'
    | '/_authenticated/palavras'
    | '/_authenticated/relatorios'
    | '/_authenticated/visitantes'
    | '/_authenticated/culto-inteligente/historico'
    | '/_authenticated/cultos/$id'
    | '/_authenticated/culto-inteligente/'
    | '/_authenticated/cultos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visitantes': {
      id: '/_authenticated/visitantes'
      path: '/visitantes'
      fullPath: '/visitantes'
      preLoaderRoute: typeof AuthenticatedVisitantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/palavras': {
      id: '/_authenticated/palavras'
      path: '/palavras'
      fullPath: '/palavras'
      preLoaderRoute: typeof AuthenticatedPalavrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/musicos': {
      id: '/_authenticated/musicos'
      path: '/musicos'
      fullPath: '/musicos'
      preLoaderRoute: typeof AuthenticatedMusicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hinos': {
      id: '/_authenticated/hinos'
      path: '/hinos'
      fullPath: '/hinos'
      preLoaderRoute: typeof AuthenticatedHinosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/congregacoes': {
      id: '/_authenticated/congregacoes'
      path: '/congregacoes'
      fullPath: '/congregacoes'
      preLoaderRoute: typeof AuthenticatedCongregacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atendimentos': {
      id: '/_authenticated/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AuthenticatedAtendimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cultos/': {
      id: '/_authenticated/cultos/'
      path: '/cultos'
      fullPath: '/cultos/'
      preLoaderRoute: typeof AuthenticatedCultosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/culto-inteligente/': {
      id: '/_authenticated/culto-inteligente/'
      path: '/culto-inteligente'
      fullPath: '/culto-inteligente/'
      preLoaderRoute: typeof AuthenticatedCultoInteligenteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cultos/$id': {
      id: '/_authenticated/cultos/$id'
      path: '/cultos/$id'
      fullPath: '/cultos/$id'
      preLoaderRoute: typeof AuthenticatedCultosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/culto-inteligente/historico': {
      id: '/_authenticated/culto-inteligente/historico'
      path: '/culto-inteligente/historico'
      fullPath: '/culto-inteligente/historico'
      preLoaderRoute: typeof AuthenticatedCultoInteligenteHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAtendimentosRoute: typeof AuthenticatedAtendimentosRoute
  AuthenticatedCongregacoesRoute: typeof AuthenticatedCongregacoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHinosRoute: typeof AuthenticatedHinosRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedMusicosRoute: typeof AuthenticatedMusicosRoute
  AuthenticatedPalavrasRoute: typeof AuthenticatedPalavrasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedVisitantesRoute: typeof AuthenticatedVisitantesRoute
  AuthenticatedCultoInteligenteHistoricoRoute: typeof AuthenticatedCultoInteligenteHistoricoRoute
  AuthenticatedCultosIdRoute: typeof AuthenticatedCultosIdRoute
  AuthenticatedCultoInteligenteIndexRoute: typeof AuthenticatedCultoInteligenteIndexRoute
  AuthenticatedCultosIndexRoute: typeof AuthenticatedCultosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAtendimentosRoute: AuthenticatedAtendimentosRoute,
  AuthenticatedCongregacoesRoute: AuthenticatedCongregacoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHinosRoute: AuthenticatedHinosRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedMusicosRoute: AuthenticatedMusicosRoute,
  AuthenticatedPalavrasRoute: AuthenticatedPalavrasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedVisitantesRoute: AuthenticatedVisitantesRoute,
  AuthenticatedCultoInteligenteHistoricoRoute:
    AuthenticatedCultoInteligenteHistoricoRoute,
  AuthenticatedCultosIdRoute: AuthenticatedCultosIdRoute,
  AuthenticatedCultoInteligenteIndexRoute:
    AuthenticatedCultoInteligenteIndexRoute,
  AuthenticatedCultosIndexRoute: AuthenticatedCultosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
